services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: moderator_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      # Expose the database port to the host machine for DBeaver access
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Service for Celery Message Broker
  redis:
    image: redis:7-alpine
    container_name: moderator_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application Service
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: moderator_api
    volumes:
      # Mount the local app directory to the container's /app directory for hot reload
      - ./app:/app/app
      - ./alembic:/alembic
      - ./alembic.ini:/alembic.ini
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

# Define a persistent named volume for PostgreSQL data
volumes:
  postgres_data:
    driver: local

