"""Initial migration with models

Revision ID: 95e1a31eab38
Revises: 
Create Date: 2025-08-29 16:09:56.046861

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95e1a31eab38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='contentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_requests_content_hash'), 'moderation_requests', ['content_hash'], unique=True)
    op.create_index(op.f('ix_moderation_requests_id'), 'moderation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_moderation_requests_user_email'), 'moderation_requests', ['user_email'], unique=False)
    op.create_table('moderation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Enum('TOXIC', 'SPAM', 'HARASSMENT', 'SAFE', name='classification'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['moderation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_results_id'), 'moderation_results', ['id'], unique=False)
    op.create_index(op.f('ix_moderation_results_request_id'), 'moderation_results', ['request_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('SLACK', 'EMAIL', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['moderation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_id'), 'notification_logs', ['id'], unique=False)
    op.create_index(op.f('ix_notification_logs_request_id'), 'notification_logs', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_request_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_moderation_results_request_id'), table_name='moderation_results')
    op.drop_index(op.f('ix_moderation_results_id'), table_name='moderation_results')
    op.drop_table('moderation_results')
    op.drop_index(op.f('ix_moderation_requests_user_email'), table_name='moderation_requests')
    op.drop_index(op.f('ix_moderation_requests_id'), table_name='moderation_requests')
    op.drop_index(op.f('ix_moderation_requests_content_hash'), table_name='moderation_requests')
    op.drop_table('moderation_requests')
    # ### end Alembic commands ###
